settings:
  title: 'Is thewebag.top down? - Status Page'
  url: 'https://status.ycistease.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: main-page # unique identifier
    name: thewebag.top
    description: 'You make the website, I will do the rest.' # default=empty
    url: 'https://thewebag.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: true # allows the title to be a link, default=true
    
  - id: yciscq-wiki # unique identifier
    name: wiki.thewebag.top
    description: 'Unofficial YCISCQ Wiki!' # default=empty
    url: 'https://wiki.thewebag.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: true # allows the title to be a link, default=true
    
  - id: cloud-page # unique identifier
    name: cloud.thewebag.top
    description: 'I will be your entertainment.' # default=empty
    url: 'https://cloud.thewebag.top/0:/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: true # allows the title to be a link, default=true
